apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderingapi-postgres-depl
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
          - name: POSTGRES_DB
            value: orderingdb
          - name: POSTGRES_USER
            value: admin
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: orderingapi-postgres
                key: PG_PASSWORD
            # value: your_password_1234
          ports:
            - containerPort: 5432
          volumeMounts:
          - name: postgres-data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: orderingapi-postgres-claim
---
apiVersion: v1
kind: Service
metadata:
  name: orderingapi-postgres-clusterip-srv
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: orderingapi-postgres-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
