FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /app

COPY Services/Catalog/CatalogApi CatalogApi/
COPY Services/Services.Common/Auth Services.Common/Auth/

RUN dotnet restore "CatalogApi/CatalogApi.csproj"
RUN dotnet publish -p:IsProduction=true "CatalogApi/CatalogApi.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app/CatalogApi/
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "CatalogApi.dll" ]