FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /app

COPY Services/Basket/BasketApi BasketApi/
COPY Services/Services.Common/Auth Services.Common/Auth/

RUN dotnet restore "BasketApi/BasketApi.csproj"
RUN dotnet publish -p:IsProduction=true "BasketApi/BasketApi.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app/BasketApi/
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "BasketApi.dll" ]