FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /app

COPY Services/Ordering/OrderingApi OrderingApi/
COPY Services/Services.Common/Auth Services.Common/Auth/

RUN dotnet restore "OrderingApi/OrderingApi.csproj"
RUN dotnet publish -p:IsProduction=true "OrderingApi/OrderingApi.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app/OrderingApi/
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "OrderingApi.dll" ]