FROM mcr.microsoft.com/dotnet/sdk:8.0 as build-env
WORKDIR /app

COPY Services/Identity/IdentityApi IdentityApi/
COPY Services/Services.Common/Auth Services.Common/Auth/

RUN dotnet restore "IdentityApi/IdentityApi.csproj"
RUN dotnet publish -p:IsProduction=true "IdentityApi/IdentityApi.csproj" -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app/IdentityApi/
COPY --from=build-env /app/out .
ENTRYPOINT [ "dotnet", "IdentityApi.dll" ]