apiVersion: v1
kind: Service
metadata:
  name: identity-np-srv
spec:
  type: NodePort
  selector:
    app: identityapi
  ports:
  - name: identityapi
    protocol: TCP
    port: 80
    targetPort: 80
